// import BackGround from "@/components/bg"
import Image from "next/image";
import '../styles/login/landingPage.css';

export const metadata = {
  title: 'PONGy',
  description: 'Generated by 1337',
}

export default function RootLayout({
  children,
}: {
  children?: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <BackGround/> */}
        <div className='bg'>
            <Image
                src="./background.svg"
                alt="PongMaster"
                priority={true}
                fill
                sizes="100vw"
                style={{
                    objectFit: "cover",
                }} />
         </div>
        {children}     
      </body>
    </html>
  )
}
