import style from '../../src/style/styles.css'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children?: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={style.body}>
        {children}     
      </body>
    </html>
  )
}
