import BackGround from "@/components/bg"

export const metadata = {
  title: 'pongmaster',
  description: 'Generated by 21',
}

export default function RootLayout({
  children,
}: {
  children?: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <BackGround/>
        {children}     
      </body>
    </html>
  )
}
